"""
src/generate_pages.py
=====================
Generate oscar2026.html (EN) and oscar2026_cn.html (CN) prediction webpages
that integrate with the oscar.css design system at mengtingwan.github.io.

Pages use oscar.css for base styles (header, layout, typography, collapsibles,
footer, grid) and only inline CSS for 2026-specific interactive components
(tabs, subtabs, nominee cards, probability bars, weight controls, charts,
method description cards).

Produces HTML pages that load oscar2026_data.js.
Each page has:
  - Commentary block (TBA placeholder)
  - Predictions tab with 5 subtabs (Overall, Stats, ML, LLM, Crowd)
  - Methods tab with 5 subtabs (Overall, Stats, ML, LLM, Crowd)

Usage:
    python -m src.generate_pages [--output-dir DIR]
"""

import argparse, json, os, textwrap

# ── Translations ──────────────────────────────────────────────────────────────

TRANS = {
'en': {
    'lang': 'en',
    'html_lang': 'en',
    'page_title': '2026 Oscar Predictions',
    'ceremony': '98th Academy Awards',
    'title': 'Who Takes Home the Oscar?',
    'subtitle': 'Four-model ensemble prediction for all 24 categories',
    'badge': 'Ceremony: March 15, 2026',
    'oscar_title': 'Oscar 2026',
    'commentary_title': 'Commentary',
    'commentary_body': 'I first started predicting the Oscars with ML about nine years ago during my PhD. After a few iterations the methodology stabilized and the project went dormant. After the ChatGPT moment, I briefly revisited it in early 2023 using a minimal setup: GPT-3.5 with zero-shot prompting and some handcrafted context, but no tools. The results ended up quite similar to what I previously got with a traditional ML pipeline.\nThis year I ran the project again as an experiment with the recent wave of coding agents. I let an agent (Claude Code) handle the full workflow: scraping historical awards-season data, doing feature engineering, training models, running some qualitative analysis via web search, and generating a website to present the results. The repo and the site this year were written entirely by the agent, though heavily prompted and guided by me.\nFrankly, it wasn\'t dramatically faster than doing it myself. Website generation is where agents clearly shine, but most other parts of the data and ML pipeline still required my guidance: natural-language debugging, asking questions, and explaining the math behind things. Part of that is probably my own baseline. I\'ve been trained to do this kind of work for years and already have a lot of muscle memory for the traditional workflow.\nI\'m no longer in academia, but I still care about how data science education might evolve. For students entering this new environment, the experience may look quite different. Projects like this have always been nice exercises because they cover the full data science workflow end to end. But as AI agents start automating more of the implementation, the core skill may shift: less about implementing models, more about asking the right questions, choosing sound technical directions, designing evaluations, and interpreting results. Students will likely need to learn not only how to design and implement models, but also how to guide agents and critically review what they produce. The fundamentals still matter. Depth and critical thinking may matter even more, and the kind of muscle memory we build may start to look very different.\n<em>ps: since this run wasn\'t much faster than doing it myself, I ended up packaging the workflow into an agent skill so it can be automated more easily next time. Not entirely sure what I\'m doing here\u2026 maybe slowly displacing myself.</em>',
    'tab_predictions': 'Predictions',
    'tab_methods': 'Prediction Methods',
    'sub_overall': 'Overall',
    'sub_stats': 'Stats',
    'sub_ml': 'ML',
    'sub_llm': 'LLM',
    'sub_crowd': 'Crowd',
    'lang_switch': '中文版',
    'lang_href': 'oscar2026_cn.html',
    'source_code': 'Source Code',
    'source_note': 'Code and website prompted by Mengting, generated by Claude Code.',
    'prev_years': 'Previous Years',
    'font_stack': "'Inter','DM Sans',system-ui,sans-serif",
    # Category short names
    'cats': {
        'Best Motion Picture of the Year':'Best Picture',
        'Best Performance by an Actor in a Leading Role':'Lead Actor',
        'Best Performance by an Actress in a Leading Role':'Lead Actress',
        'Best Performance by an Actor in a Supporting Role':'Supporting Actor',
        'Best Performance by an Actress in a Supporting Role':'Supporting Actress',
        'Best Achievement in Directing':'Director',
        'Best Original Screenplay':'Original Screenplay',
        'Best Adapted Screenplay':'Adapted Screenplay',
        'Best Achievement in Cinematography':'Cinematography',
        'Best Achievement in Film Editing':'Film Editing',
        'Best Achievement in Production Design':'Production Design',
        'Best Achievement in Costume Design':'Costume Design',
        'Best Sound':'Sound',
        'Best Achievement in Makeup and Hairstyling':'Makeup & Hair',
        'Best Achievement in Music Written for Motion Pictures (Original Score)':'Original Score',
        'Best Achievement in Music Written for Motion Pictures (Original Song)':'Original Song',
        'Best Achievement in Visual Effects':'Visual Effects',
        'Best Documentary Feature':'Documentary Feature',
        'Best Animated Feature Film':'Animated Feature',
        'Best Animated Short Film':'Animated Short',
        'Best Live Action Short Film':'Live Action Short',
        'Best Documentary Short Film':'Documentary Short',
        'Best International Feature Film':'International Film',
        'Best Casting':'Casting',
    },
    'cat_keys': {
        'picture':'Best Picture','director':'Director','actor':'Actor','actress':'Actress',
        'supp_actor':'Supp. Actor','supp_actress':'Supp. Actress',
        'original_screenplay':'Orig. Screenplay','adapted_screenplay':'Adapt. Screenplay',
        'cinematography':'Cinematography','editing':'Editing',
        'production_design':'Prod. Design','costume':'Costume','sound':'Sound',
        'makeup':'Makeup','score':'Score','song':'Song','visual_effects':'VFX',
        'documentary':'Documentary','animated':'Animated','international':'International',
    },
    # Method descriptions (TLDR)
    'stats_tldr': 'Bayesian-calibrated season award weights. For each nominee, sums P(Oscar win | season award) estimated from 2005-2025 data with Beta(1,1) smoothing.',
    'ml_tldr': 'Elastic-net / GBT logistic regression with per-category model selection via leave-one-out CV. Binary season award features + aggregate counts.',
    'llm_tldr': 'Independent LLM web research analysis conducted March 14, 2026. Not contaminated by any other model outputs.',
    'crowd_tldr': 'Gold Derby combined expert/editor/user consensus odds, cross-referenced with Variety, IndieWire, and Deadline.',
    # Method descriptions (detailed)
    'stats_detail': '''<h4>Bayesian Season Award Weight Model</h4>
<p>For each (award, category) pair, we estimate the conditional probability P(Oscar win | season award signal) from 20 years of historical data (2005–2025) using Bayesian inference.</p>
<p><strong>Prior:</strong> Beta(1,1) — a uniform prior expressing no initial preference.</p>
<p><strong>Posterior mean:</strong></p>
<div class="formula-code">P(Oscar | award) = (k + 1) / (n + 2)</div>
<p>where <em>k</em> = number of times the season award winner also won the Oscar, and <em>n</em> = total occurrences of that season award winner being an Oscar nominee. This Laplace-smoothed estimate naturally shrinks toward 0.5 for awards with limited data.</p>
<p><strong>Scoring:</strong> Win and nomination weights are estimated separately (no arbitrary nomination discount factor). A nominee's score = Σ w<sub>a,c</sub> over all their season awards, then softmax-normalized per category to produce probabilities.</p>
<p><strong>Validation:</strong> Leave-one-year-out — each held-out year uses weights calibrated from all other years, preventing information leakage.</p>
<p><strong>Top calibrated weights</strong> (from data): DGA→Director 0.82, SAG→Actor 0.86, PGA→Picture 0.64, BAFTA→Actor 0.76. Full weights saved to <code>calibrated_weights.json</code>.</p>''',
    'ml_detail': '''<h4>Elastic-Net / Gradient Boosted Tree Model</h4>
<p>Per-category model selection via leave-one-out cross-validation (LOO-CV). For each Oscar category, the pipeline trains a grid of candidate models and selects the one with the highest LOO-AUC.</p>
<p><strong>Candidates:</strong> Elastic-net logistic regression (SGDClassifier with log-loss, varying α ∈ {0.01, 0.05, 0.1} and L1-ratio ∈ {0.1, 0.5, 0.9}) + gradient boosted trees (max_depth=1, n_estimators=100).</p>
<p><strong>Features:</strong> Binary indicators for each (event, category, W/N) triple, plus aggregate counts: number of in-category wins/nominations, cross-category wins/nominations, and sweep indicators (e.g., SAG+BAFTA+GG triple crown).</p>
<p><strong>Temporal split:</strong> Strictly train on years < N, predict year N. Oscar events are excluded from features to prevent label leakage.</p>
<p><strong>Why per-category?</strong> Different categories have different predictive structures. Best Director is well-predicted by a single DGA feature; Best Picture requires many signals. Per-category selection adapts to this.</p>''',
    'llm_detail': '''<h4>Independent LLM Analysis</h4>
<p>Independent web research conducted by Claude Code on March 14, 2026 — one day before the ceremony. The LLM was given no access to Stats, ML, or Crowd model outputs.</p>
<p><strong>Research scope:</strong> Guild awards (DGA, SAG, WGA, PGA, ACE, ASC, CAS, CDG, ADG, VES, MUAHS, Annie), BAFTA, Golden Globes, Critics Choice, Spirit Awards, and trade publications (Variety, IndieWire, Hollywood Reporter, Deadline).</p>
<p><strong>Output:</strong> Per-nominee probability estimates with reasoning text and key signals. The reasoning synthesizes season award results, historical predictive rates, guild dynamics, narrative momentum, and voter patterns.</p>
<p><strong>Validation:</strong> Not possible — the LLM's knowledge of 2026 season results means it cannot fairly predict past ceremonies without data leakage. This method provides a complementary qualitative signal that the quantitative models cannot capture.</p>''',
    'crowd_detail': '''<h4>Gold Derby Crowd Consensus</h4>
<p>Gold Derby aggregates predictions from expert journalists, website editors, and thousands of users into consensus odds per nominee per category.</p>
<p><strong>Data source:</strong> <code>gold_derby_odds_2026.json</code> contains the combined consensus as of March 13, 2026. Cross-referenced with Variety, IndieWire, and Deadline prediction roundups.</p>
<p><strong>Validation:</strong> For 2020–2025, full odds distributions were collected from Gold Derby archives. Top-1 accuracy: 89.6% across 96 category-years. AUC: 0.957 across 86 category-years where full odds were available — the highest AUC of any method.</p>
<p><strong>Why so accurate?</strong> Gold Derby aggregates the "wisdom of crowds" from thousands of informed predictors. Prediction markets and expert aggregation consistently outperform individual models in forecasting tasks with diffuse information.</p>''',
    # Comparative analysis
    'comparative': '''<h4>Comparative Analysis</h4>
<p><strong>Crowd (Gold Derby)</strong> is the strongest single method — 89.6% accuracy and 0.957 AUC. It aggregates thousands of informed predictions and effectively captures the collective wisdom of the Oscar prediction community.</p>
<p><strong>ML</strong> achieves the best AUC among statistical models (0.860 on main categories), leveraging elastic-net regularization to learn which season award features matter most per category. However, it struggles with short film categories (AUC ~0.5) where there are almost no predictive features.</p>
<p><strong>Stats</strong> provides the most interpretable predictions via Bayesian-calibrated weights. Each prediction can be traced to specific season award wins. LOO-calibrated AUC of 0.854 is competitive.</p>
<p><strong>LLM</strong> cannot be historically validated but contributes qualitative judgment — narrative momentum, voter psychology, and late-breaking sentiment shifts — that no quantitative model captures.</p>
<p><strong>Key insight:</strong> If comparing ML vs Stats on the same 20 main categories, their AUCs are nearly identical (0.860 vs 0.855). ML's lower overall AUC (0.816) is entirely due to the 3 short-film categories where it performs at chance level.</p>''',
    # Ensemble description
    'ensemble_desc': '''<h4>Equal-Weight Ensemble</h4>
<p>For each nominee <em>n</em> in category <em>c</em>:</p>
<div class="formula-code">P(n) = ¼ · P<sub>stats</sub>(n) + ¼ · P<sub>ml</sub>(n) + ¼ · P<sub>llm</sub>(n) + ¼ · P<sub>crowd</sub>(n)</div>
<p>Normalized per category so probabilities sum to 1.</p>''',
},
'cn': {
    'lang': 'cn',
    'html_lang': 'zh',
    'page_title': '2026年奥斯卡预测',
    'ceremony': '第98届奥斯卡金像奖',
    'title': '谁将赢得奥斯卡？',
    'subtitle': '四模型集成预测，覆盖全部24个奖项',
    'badge': '颁奖典礼：2026年3月15日',
    'oscar_title': '奥斯卡 2026',
    'commentary_title': '评论',
    'commentary_body': '九年前我还在读博士的时候，第一次想到可以做一个用机器学习预测奥斯卡的小项目。做了几轮之后方法逐渐稳定，这个项目也就慢慢停了下来。ChatGPT 出现之后，我在 2023 年初又简单试了一次：用一个丐版的 GPT-3.5，加上一些手写的 context，做 zero-shot prompting，没有接任何外部工具，结果和以前用传统 ML pipeline 做出来的效果其实差不多。\n今年重新做这个项目，是想试试最近这一波 coding agent 到底能做到什么程度。我基本把整个流程交给了一个 agent（Claude Code）：爬取历年的颁奖季数据、做 feature engineering、训练模型、通过 web search 做一些定性分析，最后生成一个网站展示结果。今年的 repo 和网站基本都是 AI agent 写的，不过需要我大量的提示、引导和修正。\n坦白说，整体并没有比我自己做快很多。做网站确实是 agent 非常擅长的一件事，但数据和机器学习流程里的大多数步骤，仍然需要我不断指导、用自然语言一起调试、反复追问，以及解释背后的数学逻辑。某种程度上这可能也和我自己的基线有关——从本科到博士我已经被训练做这样的事情太多年，对传统 workflow 有很强的"肌肉记忆"。\n虽然已经毕业很久了，但我其实一直挺关心数据科学相关的高等教育会怎么发展。奥斯卡预测这样的项目其实是非常好的课程作业，因为它几乎完整覆盖了数据科学从头到尾的流程，而学生来做的体验肯定会和我很不一样。但当 AI agent 开始自动完成越来越多实现细节时，我们需要培养的核心能力可能也会发生变化：不再只是实现模型，而是提出正确的问题、选择合理的技术方向、设计可靠的评估方法，以及解释结果。学生可能不仅需要学会怎么做模型，也需要学会怎么引导 agent，以及批判性地看它产出的东西。基础仍然重要，但深度和判断力可能会更重要，而未来形成的"肌肉记忆"也可能会很不一样。\n<em>ps: 既然这次跑下来并没有比我自己做快多少，于是我把这个流程做成了一个 agent skill，方便以后自动化运行（可能是在一步步把自己替换掉…）</em>',
    'tab_predictions': '预测结果',
    'tab_methods': '预测方法',
    'sub_overall': '综合',
    'sub_stats': '统计',
    'sub_ml': '机器学习',
    'sub_llm': 'LLM',
    'sub_crowd': '群众',
    'lang_switch': 'English',
    'lang_href': 'oscar2026.html',
    'source_code': '源代码',
    'source_note': '代码和网页由Mengting提示、Claude Code生成。',
    'prev_years': '往年预测',
    'font_stack': "'Inter','DM Sans','PingFang SC','Microsoft YaHei',system-ui,sans-serif",
    'cats': {
        'Best Motion Picture of the Year':'最佳影片',
        'Best Performance by an Actor in a Leading Role':'最佳男主角',
        'Best Performance by an Actress in a Leading Role':'最佳女主角',
        'Best Performance by an Actor in a Supporting Role':'最佳男配角',
        'Best Performance by an Actress in a Supporting Role':'最佳女配角',
        'Best Achievement in Directing':'最佳导演',
        'Best Original Screenplay':'最佳原创剧本',
        'Best Adapted Screenplay':'最佳改编剧本',
        'Best Achievement in Cinematography':'最佳摄影',
        'Best Achievement in Film Editing':'最佳剪辑',
        'Best Achievement in Production Design':'最佳艺术指导',
        'Best Achievement in Costume Design':'最佳服装设计',
        'Best Sound':'最佳音效',
        'Best Achievement in Makeup and Hairstyling':'最佳化妆与发型',
        'Best Achievement in Music Written for Motion Pictures (Original Score)':'最佳原创配乐',
        'Best Achievement in Music Written for Motion Pictures (Original Song)':'最佳原创歌曲',
        'Best Achievement in Visual Effects':'最佳视觉效果',
        'Best Documentary Feature':'最佳纪录长片',
        'Best Animated Feature Film':'最佳动画长片',
        'Best Animated Short Film':'最佳动画短片',
        'Best Live Action Short Film':'最佳真人短片',
        'Best Documentary Short Film':'最佳纪录短片',
        'Best International Feature Film':'最佳国际影片',
        'Best Casting':'最佳选角',
    },
    'cat_keys': {
        'picture':'最佳影片','director':'导演','actor':'男主角','actress':'女主角',
        'supp_actor':'男配角','supp_actress':'女配角',
        'original_screenplay':'原创剧本','adapted_screenplay':'改编剧本',
        'cinematography':'摄影','editing':'剪辑',
        'production_design':'艺术指导','costume':'服装设计','sound':'音效',
        'makeup':'化妆','score':'配乐','song':'歌曲','visual_effects':'视效',
        'documentary':'纪录片','animated':'动画','international':'国际影片',
    },
    'stats_tldr': '贝叶斯校准的颁奖季权重模型。对每位提名者，将其颁奖季获奖信号的条件概率 P(奥斯卡|颁奖季获奖) 加权求和，概率从2005-2025年历史数据中以Beta(1,1)先验估计。',
    'ml_tldr': '弹性网络/梯度提升树逻辑回归，按类别通过留一交叉验证自动选择最优模型。特征为二值颁奖季获奖/提名指标及聚合计数。',
    'llm_tldr': '独立LLM网络调研分析（2026年3月14日）。独立调研工会奖、BAFTA、金球奖等，未使用其他模型输出。',
    'crowd_tldr': 'Gold Derby专家/编辑/用户综合共识赔率，交叉参考Variety、IndieWire、Deadline。',
    'stats_detail': '''<h4>贝叶斯颁奖季权重模型</h4>
<p>对每个（颁奖季奖项，奥斯卡类别）组合，使用贝叶斯推断从20年历史数据（2005–2025）中估计条件概率 P(奥斯卡获奖 | 颁奖季获奖)。</p>
<p><strong>先验：</strong>Beta(1,1)——均匀先验，不预设偏好。</p>
<p><strong>后验均值：</strong></p>
<div class="formula-code">P(奥斯卡 | 奖项) = (k + 1) / (n + 2)</div>
<p>其中 <em>k</em> = 颁奖季获奖者同时获得奥斯卡的次数，<em>n</em> = 该颁奖季获奖者作为奥斯卡提名人的总出现次数。Laplace平滑估计对数据有限的奖项自然收缩至0.5。</p>
<p><strong>评分：</strong>获奖和提名权重分别估计（无人为折扣因子）。提名者得分 = Σ w<sub>a,c</sub>，经Softmax归一化得到概率。</p>
<p><strong>验证：</strong>留一年交叉验证——每个留出年份使用从其他所有年份校准的权重，防止信息泄露。</p>
<p><strong>校准权重示例：</strong>DGA→导演 0.82，SAG→男主角 0.86，PGA→最佳影片 0.64，BAFTA→男主角 0.76。完整权重保存于 <code>calibrated_weights.json</code>。</p>''',
    'ml_detail': '''<h4>弹性网络 / 梯度提升树模型</h4>
<p>按类别通过留一交叉验证（LOO-CV）选择最优模型。对每个奥斯卡类别，训练一组候选模型并选择LOO-AUC最高者。</p>
<p><strong>候选模型：</strong>弹性网络逻辑回归（SGDClassifier，log-loss损失函数，α ∈ {0.01, 0.05, 0.1}，L1比率 ∈ {0.1, 0.5, 0.9}）+ 梯度提升树（max_depth=1, n_estimators=100）。</p>
<p><strong>特征：</strong>每个（颁奖活动，类别，获奖/提名）三元组的二值指标，加上聚合计数：同类别获奖/提名数、跨类别获奖/提名数、以及连冠指标（如SAG+BAFTA+GG三连冠）。</p>
<p><strong>时序分割：</strong>严格地仅使用年份 < N 的数据训练，预测第N年。奥斯卡事件本身从特征中排除以防止标签泄露。</p>
<p><strong>为何按类别选择？</strong>不同类别有不同的预测结构。最佳导演主要由DGA单一特征预测；最佳影片需要多信号综合。按类别选择模型可适应这种差异。</p>''',
    'llm_detail': '''<h4>独立LLM分析</h4>
<p>由Claude Code于2026年3月14日（颁奖典礼前一天）独立进行网络调研。LLM未接触统计模型、机器学习模型或群众赔率的输出。</p>
<p><strong>调研范围：</strong>工会奖（DGA、SAG、WGA、PGA、ACE、ASC、CAS、CDG、ADG、VES、MUAHS、Annie），BAFTA，金球奖，评论家选择奖，独立精神奖，以及行业媒体（Variety、IndieWire、好莱坞记者报、Deadline）。</p>
<p><strong>输出：</strong>每位提名者的概率估计，附带推理文本和关键信号。推理综合了颁奖季结果、历史预测准确率、工会动态、叙事势能和选民行为模式。</p>
<p><strong>验证：</strong>无法验证——LLM对2026年颁奖季结果的了解意味着无法公平地回溯预测过去的颁奖典礼。该方法提供量化模型无法捕捉的互补定性信号。</p>''',
    'crowd_detail': '''<h4>Gold Derby群众共识</h4>
<p>Gold Derby将专家记者、网站编辑和数千用户的预测聚合为每位提名者的共识赔率。</p>
<p><strong>数据来源：</strong><code>gold_derby_odds_2026.json</code>包含截至2026年3月13日的综合共识。交叉参考Variety、IndieWire和Deadline的预测汇总。</p>
<p><strong>验证：</strong>收集了2020–2025年Gold Derby存档的完整赔率分布。Top-1准确率：96个类别年中89.6%。AUC：86个有完整赔率的类别年中0.957——所有方法中最高。</p>
<p><strong>为何如此准确？</strong>Gold Derby聚合了数千位信息充分的预测者的"群众智慧"。在信息分散的预测任务中，预测市场和专家聚合始终优于单一模型。</p>''',
    'comparative': '''<h4>方法对比分析</h4>
<p><strong>群众（Gold Derby）</strong>是最强的单一方法——89.6%准确率和0.957 AUC。它聚合了数千位预测者的集体智慧，有效捕获了奥斯卡预测社区的共识信号。</p>
<p><strong>机器学习</strong>在统计模型中AUC最高（主要类别0.860），利用弹性网络正则化学习每个类别中最重要的颁奖季特征。但在短片类别中表现不佳（AUC约0.5），因为几乎没有可用的预测特征。</p>
<p><strong>统计模型</strong>提供最可解释的预测——每个预测都可追溯到具体的颁奖季获奖。LOO校准AUC为0.854，具有竞争力。</p>
<p><strong>LLM</strong>无法进行历史验证，但贡献了定性判断——叙事动能、选民心理和临阵情绪转变——这些是任何量化模型都无法捕捉的。</p>
<p><strong>关键洞察：</strong>如果在相同的20个主要类别上比较ML和统计模型，两者的AUC几乎相同（0.860 vs 0.855）。ML整体AUC较低（0.816）完全是因为3个短片类别——在这些类别中ML的表现相当于随机猜测。</p>''',
    'ensemble_desc': '''<h4>等权重集成</h4>
<p>对类别 <em>c</em> 中的每位提名者 <em>n</em>：</p>
<div class="formula-code">P(n) = ¼ · P<sub>统计</sub>(n) + ¼ · P<sub>ML</sub>(n) + ¼ · P<sub>LLM</sub>(n) + ¼ · P<sub>群众</sub>(n)</div>
<p>按类别归一化使概率总和为1。</p>''',
}
}

# ── CN Film/Person Name Mappings ──────────────────────────────────────────────

CN_NAMES = {
    "One Battle After Another":"一战再战","Sinners":"罪人","Hamnet":"哈姆奈特",
    "Frankenstein":"弗兰肯斯坦","Marty Supreme":"至尊马蒂","Sentimental Value":"情感价值",
    "The Secret Agent":"密探","F1: The Movie":"F1：狂飙飞车","Train Dreams":"火车梦",
    "Bugonia":"拯救地球","Avatar: Fire and Ash":"阿凡达：火与烬","Blue Moon":"蓝月亮",
    "KPop Demon Hunters":"K-POP：猎魔女团","Zootopia 2":"疯狂动物城2",
    "The Perfect Neighbor":"完美邻居","Mr. Nobody Against Putin":"反对普京的无名先生",
    "Cutting Through Rocks":"凿穿岩石","Come See Me in the Good Light":"向光而行",
    "The Alabama Solution":"阿拉巴马解决方案","Arco":"彩虹","Elio":"地球特派员",
    "Flow":"你好，爱美丽","Retirement Plan":"退休计划",
    "The Girl Who Cried Pearls":"哭泣珍珠的女孩","Papillon":"蝴蝶",
    "A Friend of Dorothy":"多萝西的朋友","Two People Exchanging Saliva":"交换口水的两个人",
    "Butcher's Stain":"屠夫的污渍","All the Empty Rooms":"所有空荡荡的房间",
    "If I Had Legs I'd Kick You":"如果有腿，我会踢你",
    "Sirat":"接近终点","It Was Just an Accident":"普通事故",
    "The Voice of Hind Rajab":"欣德·拉贾布之声",
    # People
    "Paul Thomas Anderson":"保罗·托马斯·安德森","Ryan Coogler":"瑞恩·库格勒",
    "Josh Safdie":"乔什·萨弗迪","Joachim Trier":"约阿希姆·提尔",
    "Michael B. Jordan":"迈克尔·B·乔丹","Leonardo DiCaprio":"莱昂纳多·迪卡普里奥",
    "Ethan Hawke":"伊桑·霍克","Wagner Moura":"瓦格纳·莫拉",
    "Jessie Buckley":"杰西·巴克利","Rose Byrne":"萝丝·拜恩",
    "Renate Reinsve":"雷娜特·赖因斯夫","Emma Stone":"艾玛·斯通",
    "Kate Hudson":"凯特·哈德森","Benicio Del Toro":"本尼西奥·德尔·托罗",
    "Jacob Elordi":"雅各布·艾洛蒂","Delroy Lindo":"德尔罗伊·林多",
    "Sean Penn":"西恩·潘","Elle Fanning":"艾丽·范宁",
    "Amy Madigan":"埃米·马迪根","Wunmi Mosaku":"乌米·马萨库",
    "Teyana Taylor":"缇雅娜·泰勒",
    "Stellan Skarsg\u00e5rd":"斯特兰·斯卡斯加德",
    "Timoth\u00e9e Chalamet":"提莫西·查拉梅",
    "Chlo\u00e9 Zhao":"赵婷",
    "Inga Ibsdotter Lilleaas":"英加·伊布斯多特·利勒亚斯",
}

CN_DOUBAN = {
    "One Battle After Another":"36176155","Sinners":"36742579","Hamnet":"35618471",
    "Frankenstein":"3262044","Marty Supreme":"36691620","Sentimental Value":"36413501",
    "The Secret Agent":"36697078","F1: The Movie":"35689244","Train Dreams":"36778356",
    "Bugonia":"35064920","Avatar: Fire and Ash":"5348089","Blue Moon":"36913754",
    "Zootopia 2":"26817136","The Perfect Neighbor":"37153809",
    "Mr. Nobody Against Putin":"37153810","Cutting Through Rocks":"36921211",
    "Come See Me in the Good Light":"37153813","The Alabama Solution":"37192173",
    "Arco":"35346268","Elio":"36090458","Retirement Plan":"37219252",
    "The Girl Who Cried Pearls":"36394662","Papillon":"36741524",
    "A Friend of Dorothy":"37335365","Two People Exchanging Saliva":"37168444",
    "Butcher's Stain":"37656528","All the Empty Rooms":"37469930",
    "Sirat":"35409362","It Was Just an Accident":"37247238",
    "The Voice of Hind Rajab":"37445715",
    "If I Had Legs I'd Kick You":"36481186",
}


# ── CN LLM Rationale Translations (nested by category_key → name) ─────────────
CN_RATIONALES = {
"picture": {
    "One Battle After Another": "横扫DGA、PGA、BAFTA最佳影片、金球奖（喜剧/音乐类）、评论家选择奖、WGA改编剧本及ACE Eddie等全部传统制度性前哨奖。在偏好投票制时代，这一组合从未失手。排名投票中，本片是《罪人》选民的共识次选，确保了较高的票仓下限。",
    "Sinners": "获得SAG最佳群戏（SAG中最直接的最佳影片预测指标）、ACE Eddie（剧情类）、WGA最佳原创剧本，并以破纪录的16项提名领跑。历史上同时获得SAG群戏+WGA原创+ACE剧情类的影片从未在最佳影片中落败。",
    "Hamnet": "获金球奖最佳剧情片，表演和技术类奖项均有斩获，但工会大奖被两部领跑影片瓜分。需排名投票中的大规模选票转移方有可能获最佳影片。",
    "Train Dreams": "获独立精神奖最佳影片，口碑极佳的独立电影，但缺乏最佳影片的主要工会奖项支持。",
    "Sentimental Value": "获9项奥斯卡提名，深受国际选民青睐，但缺乏最佳影片方面的工会奖项支持。",
    "F1: The Movie": "技术类提名强劲（音效、视觉效果、剪辑），但并非最佳影片的有力竞争者。",
    "Frankenstein": "在技术类别中表现突出，并非最佳影片竞争者。",
    "The Secret Agent": "巴西影片，获表演和国际影片提名，但非最佳影片竞争对象。",
    "Marty Supreme": "萨弗迪兄弟的话题之作，在表演和编剧类别有实力，但缺乏最佳影片的制度性支持。",
    "Bugonia": "在最佳影片竞争中存在感较低。",
},
"actor": {
    "Michael B. Jordan": "获得SAG最佳男主角——最具决定性的工会同行投票。SAG揭晓后在预测市场暴涨48点。同一部影片同时斩获SAG最佳男主角与SAG最佳群戏，构成极其强劲的信号组合。",
    "Timoth\u00e9e Chalamet": "获评论家选择奖和金球奖（喜剧/音乐类）最佳男主角，此前数月一直是大热门。SAG落败后预测急剧下滑，但仍拥有早期投票学院成员的重要支持。",
    "Leonardo DiCaprio": "虽无前哨奖获奖，但在行业媒体的学院选民访谈中被频繁提及为暗马。凭数十年学院好感度积累，在匿名选民调查中被多人提及。",
    "Ethan Hawke": "林克莱特作品的影迷最爱，获得强烈的「应该赢」呼声，但缺乏前哨奖支持。",
    "Wagner Moura": "获金球奖（剧情类）最佳男主角，凭巴西演员身份获得国际选民支持。",
},
"actress": {
    "Jessie Buckley": "横扫四大前哨奖：评论家选择奖、金球奖（剧情类）、BAFTA和SAG最佳女主角。拥有这一组合历史上从未有人失手。",
    "Renate Reinsve": "被视为共识第二选择，凭《情感价值》中的表演深受学院成员喜爱。",
    "Rose Byrne": "获独立精神奖最佳主演表演，金球奖喜剧类提名，但无重要工会奖获奖。",
    "Emma Stone": "两届奥斯卡影后，凭《拯救地球》获提名，但本周期前哨奖表现平平。",
    "Kate Hudson": "职业生涯回归叙事加持，但无重要前哨奖获奖。",
},
"supp_actor": {
    "Sean Penn": "同时获得SAG和BAFTA最佳男配角——该类别中最具预测力的两个工会信号。两届奥斯卡影帝，拥有深厚的学院认可度。",
    "Delroy Lindo": "无任何正式前哨奖获奖，但在工会全部落选情况下仍获奥斯卡提名——表明学院选民有异常强烈的热情支持。",
    "Stellan Skarsg\u00e5rd": "获金球奖最佳男配角，但SAG遗珠。瑞典资深演员在《情感价值》中的表演备受赞誉。",
    "Jacob Elordi": "获评论家选择奖最佳男配角，在《弗兰肯斯坦》中饰演怪物一角广受好评。",
    "Benicio Del Toro": "资深演员在多个影评人协会奖中胜出，但在SAG和BAFTA中被分流。",
},
"supp_actress": {
    "Amy Madigan": "获SAG和评论家选择奖最佳女配角。性格演员的突破表现，凭作品整体热度受益。",
    "Wunmi Mosaku": "凭《罪人》获BAFTA最佳女配角，是最受关注的黑马之一。",
    "Teyana Taylor": "获金球奖最佳女配角。凭《一战再战》中的表演获认可。",
    "Elle Fanning": "在《情感价值》中表现出色，但缺乏前哨奖支持。",
    "Inga Ibsdotter Lilleaas": "挪威演员凭《情感价值》获提名，前哨奖支持有限。",
},
"director": {
    "Paul Thomas Anderson": "罕见地横扫DGA、BAFTA、金球奖和评论家选择奖四大最佳导演奖。DGA是最强单一预测指标（历史准确率93%），几乎锁定最佳导演。",
    "Ryan Coogler": "《罪人》16项提名破纪录。但DGA未获奖，历史上DGA落选者在奥斯卡获胜的概率极低。",
    "Chlo\u00e9 Zhao": "前奥斯卡最佳导演得主（2021年《无依之地》）。《哈姆奈特》获多项提名但缺乏导演奖前哨支持。",
    "Joachim Trier": "凭《情感价值》获戛纳评审团大奖，但在好莱坞工会系统中存在感有限。",
    "Josh Safdie": "首次独立执导提名。影迷和评论界高度评价，但缺乏工会支持。",
},
"original_screenplay": {
    "Sinners": "横扫WGA原创剧本、BAFTA原创剧本和评论家选择奖——三大前哨奖全部获胜，历史准确率极高。",
    "Marty Supreme": "萨弗迪/布隆斯坦编剧。影迷和编剧分会高度认可，但主要前哨奖未获胜。",
    "Sentimental Value": "情感细腻的剧本。无主要前哨奖获胜。",
    "Blue Moon": "林克莱特的对话驱动型作品，编剧分会友好但缺乏前哨奖。",
    "It Was Just an Accident": "前哨奖存在感较低。",
},
"adapted_screenplay": {
    "One Battle After Another": "横扫评论家选择奖、金球奖、WGA改编剧本等全部主要改编剧本前哨奖。",
    "Hamnet": "优秀的文学改编，原著小说口碑极佳。第二选择的共识位置。",
    "Train Dreams": "获独立精神奖相关提名，精美的独立改编作品，但前哨奖有限。",
    "Bugonia": "改编剧本提名，但前哨奖存在感较低。",
    "Frankenstein": "德尔·托罗的情怀之作，并非编剧类竞争者。",
},
"cinematography": {
    "One Battle After Another": "获ASC奖、BAFTA和评论家选择奖最佳摄影——三大前哨奖全部获胜。",
    "Sinners": "在影评人协会奖中表现突出，但ASC和BAFTA输给了《一战再战》。",
    "Train Dreams": "获独立精神奖最佳摄影，自然风光摄影诗意盎然。",
    "Frankenstein": "哥特视觉风格强烈，但摄影前哨奖归属他片。",
    "Marty Supreme": "视觉风格受到好评，但无主要摄影前哨奖。",
},
"editing": {
    "One Battle After Another": "获ACE Eddie（喜剧/音乐类）和BAFTA剪辑。与最佳影片领跑地位吻合。",
    "F1: The Movie": "赛车场景的动态剪辑节奏获得业界认可。",
    "Sinners": "获ACE Eddie（剧情类）——与《一战再战》的喜剧/音乐类形成直接竞争信号。",
    "Marty Supreme": "乒乓球比赛场景的剪辑极具张力，但无前哨奖获胜。",
    "Sentimental Value": "欧洲奖项有认可，但奥斯卡剪辑类获奖概率较低。",
},
"production_design": {
    "Frankenstein": "获ADG年代片类大奖——该类别最重要的前哨指标。",
    "One Battle After Another": "获ADG当代片类大奖。如果最佳影片获奖者同时参与美术设计竞争，往往有加成效应。",
    "Hamnet": "莎士比亚时代英格兰的精细场景还原。",
    "Sinners": "1930年代美国南方的氛围营造。",
    "Marty Supreme": "纽约时代感的美术风格。",
},
"costume": {
    "Frankenstein": "获CDG年代片类、BAFTA和评论家选择奖最佳服装设计。三大前哨全部获胜。",
    "Sinners": "露丝·E·卡特是多次奥斯卡得主，1930年代南方服装设计精良。",
    "Hamnet": "伊丽莎白时代的精美服装还原。",
    "Marty Supreme": "街头时尚风格的独特服装设计。",
    "Avatar: Fire and Ash": "科幻/奇幻类服装设计。无前哨奖获胜。",
},
"sound": {
    "F1: The Movie": "获CAS（电影声音工会）、BAFTA和评论家选择奖最佳音效。赛车音效设计是本片最大技术亮点。",
    "Sinners": "获两项MPSE金卷轴奖。在音效分会有强烈的支持。",
    "Frankenstein": "获MPSE效果/拟音奖，但并非领跑者。",
    "One Battle After Another": "获提名但无主要音效前哨奖。",
    "Sirat": "沙漠战争的沉浸式音景。在技术分会中是可信的黑马。",
},
"makeup": {
    "Frankenstein": "获MUAHS特效化妆假肢奖——最相关的子类别。怪物角色的化妆是本届标志性的技术成就。",
    "Sinners": "获MUAHS年代角色化妆和年代角色发型两项大奖。但与《弗兰肯斯坦》的特效化妆相比可能略逊。",
},
"score": {
    "Sinners": "路德维格·约兰森的配乐横扫BAFTA、金球奖、评论家选择奖和格莱美奖。蓝调和爵士元素交织的恐怖氛围音乐广受赞誉。",
    "One Battle After Another": "高水准氛围配乐，但面对约兰森的全面横扫缺乏竞争力。",
},
"song": {
    "KPop Demon Hunters": "「Golden」获金球奖和评论家选择奖最佳原创歌曲。K-POP风格的洗脑旋律在全球爆火。",
    "Sinners": "蓝调风格的「I Lied to You」与影片气质高度契合，但在格莱美未获奖。",
},
"visual_effects": {
    "Avatar: Fire and Ash": "获VES视效工会最佳真人视效大奖。卡梅隆的潘多拉星球CG世界依然是业界标杆。",
    "Sinners": "获VES辅助视效奖。实拍与数字融合的超自然效果令人印象深刻。",
    "F1: The Movie": "真实F1赛车场景的实拍与CG结合。",
},
"documentary": {
    "The Perfect Neighbor": "获评论家选择奖最佳纪录片，是观众最广泛接触的提名作品。Gold Derby共识大热。",
    "Mr. Nobody Against Putin": "获BAFTA最佳纪录片——纪录片类别最强的制度性信号。",
    "Cutting Through Rocks": "历史性的首部获奥斯卡提名的伊朗纪录片。感人的女性视角叙事。",
    "Come See Me in the Good Light": "圣丹斯观众最爱。如果情感因素占上风则是黑马。",
    "The Alabama Solution": "美国刑事司法/死刑题材。前哨奖存在感有限。",
},
"animated": {
    "KPop Demon Hunters": "获Annie奖（10项全中的压倒性横扫）、金球奖和评论家选择奖最佳动画长片。近年最具突破性的动画作品之一。",
    "Zootopia 2": "迪士尼续集，票房大爆。但在奖项竞争中通常让位于更具艺术性的作品。",
    "Arco": "欧洲艺术院线动画，电影节路线的宠儿。",
    "Elio": "皮克斯出品，但在所有主要前哨奖中均败给了《猎魔女团》。",
},
"international": {
    "Sentimental Value": "获BAFTA最佳非英语影片——该类别最强的制度性信号。在多个国际影评人协会奖中胜出。",
    "The Secret Agent": "获金球奖最佳非英语影片。瓦格纳·莫拉获戛纳最佳男演员。巴西政治惊悚片。",
    "Sirat": "西班牙代表。同时获音效提名。沙漠战争的沉浸式氛围。",
    "The Voice of Hind Rajab": "突尼斯代表。巴以冲突相关的政治影片。同情票可能发挥作用。",
    "It Was Just an Accident": "法国代表。道德惊悚片。同时获原创剧本提名。",
},
"cast": {
    "Sinners": "获SAG最佳群戏——选角类别最直接的预测指标。16项提名证明了整体选角的深度和广度。",
    "Hamnet": "真兄弟出演莎士比亚兄妹的选角决定广受赞誉。",
    "One Battle After Another": "SAG男配角获奖者西恩·潘领衔，星光闪耀的群戏阵容。",
    "The Secret Agent": "国际阵容的精准组合。瓦格纳·莫拉获最佳男主角提名。",
    "Marty Supreme": "非演员为主的独特选角（阿贝尔·费拉拉、大卫·马梅特、彼得·丁拉基等），萨弗迪式的选角风格。",
},
}


def build_page(t):
    """Build complete HTML page for the given translation dict."""
    lang = t['lang']
    is_cn = lang == 'cn'

    # Convert translation dicts to JS (JSON handles all escaping)
    cats_js = json.dumps(t['cats'], ensure_ascii=False)
    cat_keys_js = json.dumps(t['cat_keys'], ensure_ascii=False)
    cn_names_js = json.dumps(CN_NAMES, ensure_ascii=False) if is_cn else '{}'
    cn_douban_js = json.dumps(CN_DOUBAN, ensure_ascii=False) if is_cn else '{}'
    cn_rationales_js = json.dumps(CN_RATIONALES, ensure_ascii=False) if is_cn else '{}'
    # Method text as JSON to avoid escaping issues
    method_text_js = json.dumps({
        'tldrs': {
            'st': t['stats_tldr'], 'ml': t['ml_tldr'],
            'll': t['llm_tldr'], 'cr': t['crowd_tldr'],
        },
        'descs': {
            'st': t['stats_detail'], 'ml': t['ml_detail'],
            'll': t['llm_detail'], 'cr': t['crowd_detail'],
        },
        'comparative': t['comparative'],
        'ensemble': t['ensemble_desc'],
    }, ensure_ascii=False)

    # Header: oscar-title and lang link differ by language
    oscar_title = t['oscar_title']
    lang_link_href = t['lang_href']
    lang_link_text = t['lang_switch']

    return f'''<!DOCTYPE html>
<html lang="{t['html_lang']}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{t['page_title']}</title>
<link rel="stylesheet" href="../assets/css/oscar.css">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,600;0,700;1,400&family=DM+Mono:wght@400;500&display=swap" rel="stylesheet">
<script src="oscar2026_data.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.2/dist/chart.umd.min.js"></script>
<style>
/* ══════════════════════════════════════════════════════════════
   2026-SPECIFIC INLINE STYLES
   Base styles (header, layout, typography, details/summary,
   footer, links, grid) come from oscar.css.
   Only interactive/2026 components are styled here.
══════════════════════════════════════════════════════════════ */
:root {{
  /* method colors */
  --stats: #2b6fd4;
  --ml: #7b52d4;
  --llm: #d06930;
  --crowd: #2a9e5e;
  /* convenience aliases from oscar.css tokens */
  --bg2: #f0eeea;
  --bg3: #e5e2dc;
  --bd: #e0e0e0;
  --bd2: #c8c4bb;
  --bd3: #b0aca3;
  --t1: #1a1a1a;
  --t2: #5a5a68;
  --t3: #8a8898;
  --r: 8px;
  --sh: 0 2px 12px rgba(0,0,0,.05);
  --ease: cubic-bezier(.4,0,.2,1);
  --win-bg: #fdf8ee;
  --win-bd: var(--gold-light);
}}

/* ── Compact Toolbar ── */
.toolbar {{
  padding: 1.2em 0 0.8em;
  border-bottom: 1px solid var(--border-light);
  margin-bottom: 1em;
}}
.toolbar-top {{
  display: flex;
  align-items: baseline;
  gap: .8em;
  margin-bottom: .6em;
}}
.toolbar-title {{
  font-family: var(--serif);
  font-size: 1.5em;
  font-weight: 700;
  color: var(--ink);
  margin: 0;
  padding: 0;
  border: none;
}}
.toolbar-badge {{
  font-size: .72rem;
  color: var(--text-muted);
}}
.toolbar-nav {{
  display: flex;
  align-items: center;
  gap: 6px;
  flex-wrap: wrap;
}}
.toolbar-sep {{
  width: 1px;
  height: 16px;
  background: var(--border);
  flex-shrink: 0;
}}
.wctl-toggle {{
  font-size: .72rem;
  color: var(--text-muted);
  margin-left: auto;
}}

/* ── Tabs (main) ── */
.oscar-tabs {{
  display: flex;
  gap: 0;
  flex-shrink: 0;
}}
.oscar-tab {{
  background: none;
  border: none;
  border-bottom: 2px solid transparent;
  padding: 4px 12px;
  font-family: var(--sans);
  font-size: .78rem;
  font-weight: 500;
  color: var(--text-muted);
  cursor: pointer;
  transition: all .2s;
}}
.oscar-tab:hover {{ color: var(--text); }}
.oscar-tab.on {{
  color: var(--gold);
  border-bottom-color: var(--gold);
  font-weight: 600;
}}

/* ── Subtabs ── */
.stabs {{
  display: flex;
  gap: 3px;
  flex-wrap: wrap;
}}
.stab {{
  padding: 3px 10px;
  border-radius: 4px;
  font-size: .7rem;
  font-weight: 500;
  color: var(--text-muted);
  background: var(--bg-warm);
  border: 1px solid transparent;
  cursor: pointer;
  transition: all .15s;
}}
.stab:hover {{ color: var(--text); }}
.stab.on {{ font-weight: 600; color: #fff; border-color: transparent; }}
.stab.s-ov.on {{ background: var(--gold); }}
.stab.s-st.on {{ background: var(--stats); }}
.stab.s-ml.on {{ background: var(--ml); }}
.stab.s-ll.on {{ background: var(--llm); }}
.stab.s-cr.on {{ background: var(--crowd); }}

/* ── Panels ── */
.panel {{ display: none; }}
.panel.on {{ display: block; }}

/* ── Commentary ── */
.commentary {{
  font-size: .82rem;
  color: var(--text-muted);
  margin: 0 0 .6em;
  padding: 0;
}}
.commentary a {{
  color: var(--gold);
}}
.commentary-details {{
  margin: 0 0 1.2em;
  background: var(--bg-warm);
  border: 1px solid var(--border-light);
  border-radius: 4px;
}}
.commentary-details summary {{
  font-size: .82rem;
  color: var(--text-light);
  padding: .5em .8em;
}}
.commentary-details > div {{
  padding: .4em 1em 1em;
  font-size: .86rem;
  color: var(--text);
  line-height: 1.85;
}}
.commentary-details > div p {{
  margin-bottom: .7em;
}}

/* ── Nominee Grid ── */
.ngrid {{
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(140px, 1fr));
  gap: 10px;
  margin-bottom: 12px;
}}
@media (max-width: 500px) {{ .ngrid {{ grid-template-columns: repeat(2, 1fr); }} }}

.ncard {{
  border-radius: var(--r);
  background: var(--bg-warm);
  border: 1.5px solid var(--border);
  overflow: hidden;
  position: relative;
  transition: transform .2s, border-color .2s, box-shadow .2s;
}}
.ncard:hover {{
  transform: translateY(-3px);
  box-shadow: 0 6px 16px rgba(0,0,0,.07);
}}
.ncard.win {{
  border-color: var(--gold-light);
  background: var(--win-bg);
}}
.troph {{
  position: absolute;
  top: 5px;
  right: 5px;
  z-index: 4;
  width: 22px;
  height: 22px;
  border-radius: 50%;
  background: rgba(0,0,0,.7);
  border: 1px solid var(--gold-light);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: .7rem;
}}
.poster {{
  width: 100%;
  aspect-ratio: 2/3;
  overflow: hidden;
  background: var(--bg3);
  position: relative;
}}
.poster img {{
  width: 100%;
  height: 100%;
  object-fit: cover;
  filter: grayscale(10%) brightness(.96);
}}
.ncard:hover .poster img, .ncard.win .poster img {{ filter: none; }}
.pov {{
  position: absolute;
  bottom: 0;
  inset-inline: 0;
  padding: 20px 6px 4px;
  background: linear-gradient(transparent, rgba(0,0,0,.7));
  text-align: right;
}}
.pnum {{
  font-family: var(--serif);
  font-size: .95rem;
  font-weight: 700;
  color: #e0dcd4;
}}
.ncard.win .pnum {{ color: #e8c560; }}
.bwrap {{ padding: 0 6px 2px; }}
.btrack {{
  background: rgba(0,0,0,.08);
  border-radius: 2px;
  height: 2.5px;
  overflow: hidden;
}}
.bfill {{
  height: 100%;
  border-radius: 2px;
  transition: width .5s var(--ease);
}}
.ncard.win .bfill {{
  background: linear-gradient(90deg, var(--gold-light), var(--gold));
}}
.ncard:not(.win) .bfill {{
  background: var(--bd3);
  opacity: .6;
}}
.nbody {{ padding: 5px 7px 7px; }}
.nname {{
  font-size: .76rem;
  font-weight: 600;
  line-height: 1.25;
  color: var(--charcoal);
}}
.ncard.win .nname {{ color: var(--gold); font-weight: 700; }}
.nfilm {{
  font-size: .65rem;
  color: var(--text-light);
  font-style: italic;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}}
.wtags {{ display: flex; flex-wrap: wrap; gap: 2px; margin-top: 2px; }}
.wtag {{
  font-size: .52rem;
  font-weight: 600;
  padding: 1px 4px;
  border-radius: 2px;
  background: rgba(42,158,94,.08);
  color: var(--crowd);
  border: 1px solid rgba(42,158,94,.15);
}}
.wtag.nom {{ color: var(--text-muted); background: transparent; }}

/* ── Rationale (inside details/summary from oscar.css) ── */
.rat-wrap {{
  margin-top: 10px;
}}
.rat-wrap details {{
  margin: 0 0 1px;
  border-radius: 0;
}}
.rat-wrap details:first-child {{
  border-radius: var(--r) var(--r) 0 0;
}}
.rat-wrap details:last-child {{
  border-radius: 0 0 var(--r) var(--r);
}}
.rat-wrap details:only-child {{
  border-radius: var(--r);
}}
.rat-wrap summary {{
  display: flex;
  align-items: center;
  gap: 8px;
}}
.rat-wrap summary .rname {{
  font-weight: 600;
  color: var(--text);
  flex: 1;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}}
.rat-wrap summary .rname.win {{ color: var(--gold); }}
.rat-wrap summary .rpct {{
  font-family: 'DM Mono', monospace;
  font-size: .7rem;
  color: var(--text-muted);
  flex-shrink: 0;
}}
.rat-body {{
  font-size: .8rem;
  color: var(--text-light);
  line-height: 1.7;
}}
.rat-body p {{ margin-bottom: 4px; }}
.rat-sigs {{
  display: flex;
  flex-wrap: wrap;
  gap: 3px;
  margin-top: 5px;
}}
.rsig {{
  font-size: .58rem;
  font-weight: 500;
  padding: 2px 5px;
  border-radius: 3px;
  background: rgba(42,158,94,.08);
  color: var(--crowd);
  border: 1px solid rgba(42,158,94,.15);
}}
.rat-unc {{
  font-size: .74rem;
  color: var(--text-muted);
  font-style: italic;
  margin-top: 4px;
}}

/* ── Weight Controls ── */
.wctl {{
  background: white;
  border: 1px solid var(--border);
  border-radius: var(--r);
  padding: 14px 18px;
  margin-bottom: 16px;
}}
.wctl-note {{
  font-size: .74rem;
  color: var(--text-muted);
  line-height: 1.6;
  margin-bottom: 10px;
  font-style: italic;
}}
.wctl-grid {{
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
  align-items: center;
}}
.wctl-item {{
  display: flex;
  align-items: center;
  gap: 5px;
  font-size: .74rem;
  font-weight: 600;
}}
.wctl-item.c-st {{ color: var(--stats); }}
.wctl-item.c-ml {{ color: var(--ml); }}
.wctl-item.c-ll {{ color: var(--llm); }}
.wctl-item.c-cr {{ color: var(--crowd); }}
.wctl-item input[type=number] {{
  width: 46px;
  padding: 3px 4px;
  border: 1px solid var(--border);
  border-radius: 4px;
  background: var(--bg-warm);
  color: var(--text);
  font-family: 'DM Mono', monospace;
  font-size: .74rem;
  text-align: center;
  outline: none;
}}
.wctl-item input:focus {{ border-color: var(--gold); }}
.wctl-item .wnorm {{
  font-family: 'DM Mono', monospace;
  font-size: .7rem;
  color: var(--gold);
  font-weight: 700;
  min-width: 32px;
  transition: all .3s;
}}
.wctl-btn {{
  padding: 4px 12px;
  border-radius: 5px;
  font-size: .7rem;
  font-weight: 600;
  border: 1px solid rgba(160,133,48,.2);
  background: var(--gold-faint);
  color: var(--gold);
  cursor: pointer;
  transition: all .15s;
}}
.wctl-btn:hover {{ background: rgba(160,133,48,.12); }}
.wctl-summary {{
  font-size: .72rem;
  color: var(--text-light);
  margin-top: 8px;
  padding: 6px 10px;
  background: var(--bg-warm);
  border-radius: 6px;
  font-family: 'DM Mono', monospace;
  transition: all .3s;
}}
.wctl-summary b {{ color: var(--gold); }}
@keyframes wflash {{ 0% {{ background: rgba(160,133,48,.15); }} 100% {{ background: var(--bg-warm); }} }}
.wctl-flash {{ animation: wflash .6s var(--ease); }}

/* ── Method Cards ── */
.mcards {{
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 12px;
  margin: 16px 0;
}}
.mcard {{
  background: white;
  border: 1px solid var(--border);
  border-radius: var(--r);
  padding: 16px;
  transition: all .2s var(--ease);
}}
.mcard:hover {{
  border-color: var(--bd2);
  transform: translateY(-2px);
  box-shadow: var(--sh);
}}
.mcard-tag {{
  display: inline-block;
  font-size: .62rem;
  font-weight: 700;
  letter-spacing: .4px;
  padding: 2px 7px;
  border-radius: 4px;
  margin-bottom: 6px;
  text-transform: uppercase;
}}
.mcard-tag.st {{ background: rgba(43,111,212,.08); color: var(--stats); }}
.mcard-tag.ml {{ background: rgba(123,82,212,.08); color: var(--ml); }}
.mcard-tag.ll {{ background: rgba(208,105,48,.08); color: var(--llm); }}
.mcard-tag.cr {{ background: rgba(42,158,94,.08); color: var(--crowd); }}
.mcard-name {{
  font-family: var(--serif);
  font-size: .95rem;
  font-weight: 600;
  margin-bottom: 6px;
}}
.mcard-desc {{
  font-size: .76rem;
  color: var(--text-light);
  line-height: 1.6;
}}

/* ── Method Detail ── */
.mdesc {{
  background: white;
  border: 1px solid var(--border);
  border-radius: var(--r);
  padding: 20px 24px;
  margin: 16px 0;
  font-size: .82rem;
  color: var(--text-light);
  line-height: 1.75;
}}
.mdesc h4 {{
  font-family: var(--serif);
  font-size: 1.05rem;
  color: var(--text);
  margin-bottom: 8px;
}}
.mdesc p {{ margin-bottom: 8px; }}

/* ── Formula code ── */
.formula-code {{
  font-family: 'DM Mono', monospace;
  font-size: .78rem;
  background: var(--bg-warm);
  border: 1px solid var(--border-light);
  border-radius: 6px;
  padding: 10px 14px;
  margin: 10px 0;
  line-height: 1.7;
}}

/* ── Tables ── */
.tbl {{
  width: 100%;
  border-collapse: collapse;
  font-size: .78rem;
  margin: 12px 0;
}}
.tbl th {{
  text-align: left;
  padding: 6px 8px;
  background: var(--bg3);
  color: var(--text-muted);
  font-size: .62rem;
  text-transform: uppercase;
  letter-spacing: .6px;
  border-bottom: 1px solid var(--bd2);
}}
.tbl td {{
  padding: 6px 8px;
  border-bottom: 1px solid var(--border-light);
}}
.tbl tr:hover td {{ background: rgba(0,0,0,.02); }}

/* ── Chart Box ── */
.chartbox {{
  background: white;
  border: 1px solid var(--border);
  border-radius: var(--r);
  padding: 16px;
  margin: 12px 0;
}}
.chart-title {{
  font-size: .74rem;
  font-weight: 600;
  color: var(--text-light);
  text-transform: uppercase;
  letter-spacing: .6px;
  margin-bottom: 12px;
}}

/* ── Year accordion ── */
.yritem {{
  border: 1px solid var(--border);
  border-radius: var(--r);
  overflow: hidden;
  margin-bottom: 6px;
}}
.yrhdr {{
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 14px;
  background: var(--bg-warm);
  cursor: pointer;
  user-select: none;
  font-size: .8rem;
}}
.yrhdr:hover {{ background: var(--bg3); }}
.yrhdr h3 {{
  font-family: var(--serif);
  font-size: .9rem;
  font-weight: 600;
  flex: 1;
  margin: 0;
  padding: 0;
  border: none;
}}
.yrhdr .ychev {{
  font-size: .55rem;
  color: var(--text-light);
  transition: transform .2s;
}}
.yrhdr.open .ychev {{ transform: rotate(180deg); }}
.yrtblwrap {{ display: none; overflow-x: auto; }}
.yrtblwrap.open {{ display: block; }}

/* ── Status icons ── */
.ico-ok {{ color: var(--crowd); }}
.ico-ms {{ color: var(--llm); }}

/* ── Category confidence badge ── */
.cat-conf {{
  font-family: 'DM Mono', monospace;
  font-size: .68rem;
  color: var(--text-muted);
  background: var(--bg3);
  padding: 2px 6px;
  border-radius: 3px;
  margin-left: 8px;
}}

/* ── Section divider ── */
.sec {{
  margin: 28px 0 16px;
  padding-bottom: 10px;
  border-bottom: 1px solid var(--border-light);
  position: relative;
}}
.sec::after {{
  content: '';
  position: absolute;
  bottom: -1px;
  left: 0;
  width: 40px;
  height: 2px;
  background: var(--gold-light);
}}
.sec h2 {{
  font-family: var(--serif);
  font-size: 1.3rem;
  font-weight: 700;
  color: var(--gold);
}}

/* ── Responsive adjustments ── */
@media screen and (max-width: 680px) {{
  .oscar-hero {{ padding: 1.8em 1em 1.5em; }}
  .oscar-hero h1 {{ font-size: 1.6rem; }}
  .oscar-tabs {{ gap: 0; }}
  .oscar-tab {{ padding: 6px 12px; font-size: .76rem; }}
  .stabs {{ gap: 3px; }}
  .stab {{ padding: 4px 10px; font-size: .7rem; }}
  .ngrid {{ grid-template-columns: repeat(auto-fill, minmax(120px, 1fr)); }}
  .wctl-grid {{ gap: 8px; }}
  .mcards {{ grid-template-columns: 1fr; }}
}}
@media screen and (max-width: 420px) {{
  .ngrid {{ grid-template-columns: repeat(2, 1fr); }}
}}
</style>
</head>
<body>

<!-- ── Oscar Header (from oscar.css) ── -->
<header class="oscar-header">
  <div class="oscar-header-inner">
    <a href="../" class="oscar-home">Mengting Wan <span class="oscar-name-cn">(万梦婷)</span></a>
    <span class="oscar-sep">/</span>
    <span class="oscar-title">{oscar_title}</span>
    <div class="oscar-nav">
      <div class="oscar-dropdown">
        <button class="oscar-dropdown-btn">All Years <span class="arrow">&#9662;</span></button>
        <div class="oscar-dropdown-menu">
          <a href="oscar2026.html" class="active">2026</a>
          <a href="oscar2023.html">2023</a>
          <a href="oscar2021.html">2021</a>
          <a href="oscar2020.html">2020</a>
          <a href="oscar2019.html">2019</a>
          <a href="oscar2018.html">2018</a>
          <a href="oscar2017.html">2017</a>
        </div>
      </div>
      <a href="{lang_link_href}" class="oscar-lang">{lang_link_text}</a>
    </div>
  </div>
</header>

<!-- ── Wrapper / Main / Inner (matches legacy layout from oscar.css) ── -->
<div id="wrapper">
<div id="main">
<div class="inner">

<!-- ── Compact Toolbar: title + all navigation in one block ── -->
<div class="toolbar">
  <div class="toolbar-top">
    <h2 class="toolbar-title">{t['title']}</h2>
    <span class="toolbar-badge">{t['badge']}</span>
  </div>
  <div class="toolbar-nav">
    <div class="oscar-tabs" id="main-tabs">
      <button class="oscar-tab on" onclick="showMain('pred')">{t['tab_predictions']}</button>
      <button class="oscar-tab" onclick="showMain('meth')">{t['tab_methods']}</button>
    </div>
    <span class="toolbar-sep"></span>
    <div class="stabs" id="active-stabs">
      <button class="stab s-ov on" onclick="showSub(CUR_MAIN,'ov')">{t['sub_overall']}</button>
      <button class="stab s-st" onclick="showSub(CUR_MAIN,'st')">{t['sub_stats']}</button>
      <button class="stab s-ml" onclick="showSub(CUR_MAIN,'ml')">{t['sub_ml']}</button>
      <button class="stab s-ll" onclick="showSub(CUR_MAIN,'ll')">{t['sub_llm']}</button>
      <button class="stab s-cr" onclick="showSub(CUR_MAIN,'cr')">{t['sub_crowd']}</button>
    </div>
    <a href="#" class="wctl-toggle" id="wctl-toggle" onclick="event.preventDefault();document.getElementById('wctl').style.display=document.getElementById('wctl').style.display==='none'?'block':'none'">{'Weights' if not is_cn else '权重'} &#9881;</a>
  </div>
</div>

<!-- ── Weight Controls (hidden by default, toggled via link) ── -->
<div class="wctl" id="wctl" style="display:none">
  <div class="wctl-note">{
    'Adjust weights and click Apply. Rationales use equal weights.'
    if not is_cn else
    '调整权重后点击应用。分析文本基于等权重生成。'
  }</div>
  <div class="wctl-grid">
    <div class="wctl-item c-st"><span>Stats</span><input type="number" id="w-st" min="0" max="100" value="25" step="1"><span class="wnorm" id="wn-st">25%</span></div>
    <div class="wctl-item c-ml"><span>ML</span><input type="number" id="w-ml" min="0" max="100" value="25" step="1"><span class="wnorm" id="wn-ml">25%</span></div>
    <div class="wctl-item c-ll"><span>LLM</span><input type="number" id="w-ll" min="0" max="100" value="25" step="1"><span class="wnorm" id="wn-ll">25%</span></div>
    <div class="wctl-item c-cr"><span>Crowd</span><input type="number" id="w-cr" min="0" max="100" value="25" step="1"><span class="wnorm" id="wn-cr">25%</span></div>
    <button class="wctl-btn" onclick="applyWeights()">{'Apply' if not is_cn else '应用'} &rarr;</button>
    <button class="wctl-btn" onclick="resetWeights()">{'Reset' if not is_cn else '重置'}</button>
  </div>
  <div class="wctl-summary" id="wctl-sum">Stats <b>25%</b> + ML <b>25%</b> + LLM <b>25%</b> + Crowd <b>25%</b></div>
</div>

<!-- ── Commentary (compact) ── -->
<p class="commentary"><a href="https://github.com/MengtingWan/oscar/tree/master">{t['source_code']}</a>. {t['source_note']}</p>
<details class="commentary-details">
  <summary>{t['commentary_title']}</summary>
  <div>{''.join('<p>' + p + '</p>' for p in t['commentary_body'].split(chr(10)) if p.strip())}</div>
</details>

<!-- ══════════ PREDICTIONS ══════════ -->
<div class="panel on" id="p-pred">
  <div id="pred-content"></div>
</div>

<!-- ══════════ METHODS ══════════ -->
<div class="panel" id="p-meth">
  <div id="meth-content"></div>
</div>

</div><!-- /.inner -->
</div><!-- /#main -->
</div><!-- /#wrapper -->

<!-- ── Footer (oscar.css .oscar-footer) ── -->
<footer class="oscar-footer">
  <p>&copy; {t['badge']}</p>
</footer>

<script>
const D = window.OSCAR_DATA;
const LANG = '{lang}';
const CN_NAMES = {cn_names_js};
const CN_DOUBAN = {cn_douban_js};
const CN_RAT = {cn_rationales_js};
const CATS = {cats_js};
const CAT_KEYS = {cat_keys_js};
const METHODS = ['ov','st','ml','ll','cr'];
const METHOD_LABELS = {{ov:'{t["sub_overall"]}',st:'{t["sub_stats"]}',ml:'{t["sub_ml"]}',ll:'{t["sub_llm"]}',cr:'{t["sub_crowd"]}'}};
const METHOD_COLORS = {{st:'var(--stats)',ml:'var(--ml)',ll:'var(--llm)',cr:'var(--crowd)',ov:'var(--gold)'}};
const MT = {method_text_js};

let CUR_MAIN = 'pred', CUR_SUB = 'ov';
let W = {{s:0.25, m:0.25, l:0.25, c:0.25}};

/* ── Helpers ── */
function pct(v){{return Math.round((v||0)*100)+'%';}}
function pcls(p){{return p>=.65?'ph':p>=.45?'pm':'pl';}}
function cn(name){{return LANG==='cn'&&CN_NAMES[name]?CN_NAMES[name]:name;}}
function dbUrl(name){{const id=CN_DOUBAN[name];return id?'https://movie.douban.com/subject/'+id+'/':'';}}
function sc(c){{return CATS[c]||c;}}
function ck(k){{return CAT_KEYS[k]||k;}}

const EV_SHORT={{'Directors Guild of America, USA':'DGA','PGA Awards':'PGA','Screen Actors Guild Awards':'SAG','BAFTA Awards':'BAFTA','Golden Globes, USA':'GG','Broadcast Film Critics Association Awards':'CC','Writers Guild of America, USA':'WGA','American Cinema Editors, USA':'ACE','Art Directors Guild':'ADG','Costume Designers Guild Awards':'CDG','American Society of Cinematographers, USA':'ASC','Cinema Audio Society, USA':'CAS','Visual Effects Society Awards':'VES','Annie Awards':'Annie','Grammy Awards':'Grammy','Film Independent Spirit Awards':'Spirit','National Society of Film Critics Awards, USA':'NSFC','Online Film Critics Society Awards':'OFCS'}};
function evTag(w){{const i=w.indexOf('::');if(i<0)return w;const ev=w.slice(0,i),rest=w.slice(i+2),isN=rest.endsWith('::N');return(EV_SHORT[ev]||ev.split(',')[0].slice(0,8))+(isN?' Nom':' Win');}}

/* ── Ensemble ── */
function ensProb(cat){{
  return cat.nominees.map(n=>W.s*n.stats_prob+W.m*n.ml_prob+W.l*n.llm_prob+W.c*n.gd_prob);
}}
function applyWeights(){{
  const rs=Math.max(0,+(document.getElementById('w-st').value)||0);
  const rm=Math.max(0,+(document.getElementById('w-ml').value)||0);
  const rl=Math.max(0,+(document.getElementById('w-ll').value)||0);
  const rc=Math.max(0,+(document.getElementById('w-cr').value)||0);
  const tot=rs+rm+rl+rc||1;
  W={{s:rs/tot,m:rm/tot,l:rl/tot,c:rc/tot}};
  // Update normalized displays
  const p=v=>Math.round(v*100)+'%';
  document.getElementById('wn-st').textContent=p(W.s);
  document.getElementById('wn-ml').textContent=p(W.m);
  document.getElementById('wn-ll').textContent=p(W.l);
  document.getElementById('wn-cr').textContent=p(W.c);
  // Update summary with flash
  const lbl=LANG==='cn'?'\\u96c6\\u6210':'Ensemble';
  const sum=document.getElementById('wctl-sum');
  sum.innerHTML=lbl+': Stats <b>'+p(W.s)+'</b> + ML <b>'+p(W.m)+'</b> + LLM <b>'+p(W.l)+'</b> + Crowd <b>'+p(W.c)+'</b>';
  sum.classList.remove('wctl-flash');void sum.offsetWidth;sum.classList.add('wctl-flash');
  buildContent();
}}
function resetWeights(){{
  document.getElementById('w-st').value=25;document.getElementById('w-ml').value=25;
  document.getElementById('w-ll').value=25;document.getElementById('w-cr').value=25;
  W={{s:0.25,m:0.25,l:0.25,c:0.25}};applyWeights();
}}
function getProb(cat,nom,method){{
  if(method==='ov'){{const ps=ensProb(cat);const t=ps.reduce((a,b)=>a+b,0);const i=cat.nominees.indexOf(nom);return t>0?ps[i]/t:1/cat.nominees.length;}}
  if(method==='st')return nom.stats_prob;if(method==='ml')return nom.ml_prob;
  if(method==='ll')return nom.llm_prob;if(method==='cr')return nom.gd_prob;return 0;
}}
function topNom(cat,method){{let b=null,bp=-1;cat.nominees.forEach(n=>{{const p=getProb(cat,n,method);if(p>bp){{bp=p;b=n;}}}});return b;}}

/* ── Rationale per method ── */
function getRationale(nom,method,catKey){{
  if(method==='st'){{
    const r=nom.stats_rationale;if(!r)return'';
    const wins=r.season_wins.map(w=>evTag(w.award+'::'+w.category+'::W'));
    const noms=r.season_nominations.map(w=>evTag(w.award+'::'+w.category+'::N'));
    if(wins.length)return(LANG==='cn'?'\\u83b7\\u5f97\\uff1a':'Won: ')+wins.join(', ')+(noms.length?(LANG==='cn'?'\\u3002\\u63d0\\u540d\\uff1a':'. Nominated: ')+noms.join(', '):'');
    if(noms.length)return(LANG==='cn'?'\\u63d0\\u540d\\uff1a':'Nominated: ')+noms.join(', ');
    return LANG==='cn'?'\\u65e0\\u988c\\u5956\\u5b63\\u4fe1\\u53f7':'No season signals';
  }}
  if(method==='ml'){{
    const r=nom.ml_rationale;if(!r||!r.features||!r.features.length)return'';
    const fs=r.features.slice(0,4).map(f=>f.display+' ('+(f.coefficient>0?'+':'')+f.coefficient.toFixed(2)+')');
    return(LANG==='cn'?'\\u5173\\u952e\\u7279\\u5f81\\uff1a':'Key features: ')+fs.join('; ')+(r.model_selected?' ['+r.model_selected+']':'');
  }}
  if(method==='ll'||method==='ov'){{
    // CN: use category-specific translation if available
    const cnCat=CN_RAT[catKey];
    if(LANG==='cn'&&cnCat&&cnCat[nom.name])return cnCat[nom.name];
    const llm=nom.llm_rationale.reasoning||'';
    if(llm)return llm;
    if(method==='ov'){{
      const sw=nom.stats_rationale.season_wins;
      if(sw&&sw.length)return(LANG==='cn'?'\\u83b7\\u5f97\\uff1a':'Won: ')+sw.map(w=>evTag(w.award+'::'+w.category+'::W')).join(', ');
    }}
    return'';
  }}
  if(method==='cr'){{
    const r=nom.gd_rationale;if(!r||r.raw_odds==null)return'';
    return(LANG==='cn'?'\\u4e13\\u5bb6\\u5171\\u8bc6\\uff1a':'Expert consensus: ')+pct(r.raw_odds)+' ('+
      (LANG==='cn'?'\\u6392\\u540d':'rank')+' '+r.odds_rank+'/'+r.n_candidates+')';
  }}
  return'';
}}

/* ── Tab switching ── */
function showMain(id){{
  CUR_MAIN=id;CUR_SUB='ov';
  document.querySelectorAll('#main-tabs .oscar-tab').forEach((b,i)=>b.classList.toggle('on',i===(id==='pred'?0:1)));
  document.querySelectorAll('.panel').forEach(p=>p.classList.remove('on'));
  document.getElementById('p-'+id).classList.add('on');
  document.querySelectorAll('#active-stabs .stab').forEach((b,i)=>b.classList.toggle('on',i===0));
  // Hide weight controls when not on Predictions/Overall
  const wctl=document.getElementById('wctl');
  if(wctl&&id!=='pred')wctl.style.display='none';
  buildContent();
}}
function showSub(main,sub){{
  CUR_SUB=sub;
  document.querySelectorAll('#active-stabs .stab').forEach(b=>{{
    b.classList.toggle('on',b.classList.contains('s-'+sub));
  }});
  buildContent();
}}
let methBuilt={{}};
function buildContent(){{
  if(CUR_MAIN==='pred')buildPredictions();
  else buildMethods();
  // Refresh the category nav bar with updated winners
  if(window.refreshOscarNav)window.refreshOscarNav();
}}

/* ── Build Predictions ── */
function buildPredictions(){{
  const wrap=document.getElementById('pred-content');wrap.innerHTML='';
  const m=CUR_SUB;

  D.categories.forEach((cat,catIdx)=>{{
    const w=topNom(cat,m);
    // Use <details><summary> for collapsible categories (styled by oscar.css)
    const det=document.createElement('details');
    det.setAttribute('data-cat',cat.category);
    det.setAttribute('data-winner',cn(w.name));
    det.id='cat-'+cat.category_key;
    // Auto-open first 6 categories
    if(catIdx<6)det.setAttribute('open','');
    const sum=document.createElement('summary');
    // Show winner name in the summary line — clean and readable
    sum.innerHTML=sc(cat.category)+': <span style="color:var(--gold);font-weight:600">'+cn(w.name)+'</span> <span class="cat-conf">'+pct(getProb(cat,w,m))+'</span>';
    det.appendChild(sum);
    // Body inside details
    const body=document.createElement('div');
    body.style.padding='0.8em 1.1em';
    // Grid
    const grid=document.createElement('div');grid.className='ngrid';
    cat.nominees.forEach((nom,i)=>{{
      const p=getProb(cat,nom,m),isW=nom===w;
      const card=document.createElement('div');card.className='ncard'+(isW?' win':'');
      const dbn=LANG==='cn'?dbUrl(nom.name):'';
      const ttc=(nom.primaryCodes||[]).find(c=>c.startsWith('tt'))||(nom.secondaryCodes||[]).find(c=>c.startsWith('tt'));
      const nmc=(nom.primaryCodes||[]).find(c=>c.startsWith('nm'))||(nom.secondaryCodes||[]).find(c=>c.startsWith('nm'));
      const href=dbn||(nmc?'https://www.imdb.com/name/'+nmc:ttc?'https://www.imdb.com/title/'+ttc:'');
      const lA=href?'<a href="'+href+'" target="_blank" rel="noopener">':'',lZ=href?'</a>':'';
      const dispN=cn(nom.name),dispS=cn(nom.secondary||'');
      const img=nom.imageUrl?'<div class="poster">'+lA+'<img src="'+nom.imageUrl+'" loading="lazy" onerror="this.style.display=\\'none\\'">'+lZ+'<div class="pov"><span class="pnum">'+pct(p)+'</span></div></div>':'<div class="poster"><div class="pov"><span class="pnum">'+pct(p)+'</span></div></div>';
      const tags=(m==='ov'||m==='st')?(nom.wins||[]).slice(0,4).map(wt=>'<span class="wtag'+(wt.endsWith('::N')?' nom':'')+'">'+evTag(wt)+'</span>').join(''):'';
      card.innerHTML=(isW?'<div class="troph">\\uD83C\\uDFC6</div>':'')+img
        +'<div class="bwrap"><div class="btrack"><div class="bfill" style="width:'+p*100+'%"></div></div></div>'
        +'<div class="nbody"><div class="nname">'+dispN+'</div><div class="nfilm">'+dispS+'</div>'
        +(tags?'<div class="wtags">'+tags+'</div>':'')+'</div>';
      grid.appendChild(card);
    }});
    body.appendChild(grid);
    // Rationale — item-by-item, collapsible (using details/summary styled by oscar.css)
    const sorted=[...cat.nominees].sort((a,b)=>getProb(cat,b,m)-getProb(cat,a,m));
    const hasAny=sorted.some(nom=>getRationale(nom,m,cat.category_key));
    if(hasAny){{
      const rw=document.createElement('div');rw.className='rat-wrap';
      sorted.forEach((nom,ri)=>{{
        const reason=getRationale(nom,m,cat.category_key);
        const p=getProb(cat,nom,m),isW=nom===w;
        const rdet=document.createElement('details');
        if(ri===0)rdet.setAttribute('open','');
        const rsum=document.createElement('summary');
        rsum.innerHTML='<span class="rname'+(isW?' win':'')+'">'+cn(nom.name)+'</span><span class="rpct">'+pct(p)+'</span>';
        rdet.appendChild(rsum);
        if(reason){{
          const bd=document.createElement('div');bd.className='rat-body';
          let html='<p>'+reason+'</p>';
          const sigs=(m==='ll'||m==='ov')?(nom.llm_rationale.key_signals||[]):[];
          if(sigs.length)html+='<div class="rat-sigs">'+sigs.map(s=>'<span class="rsig">'+s+'</span>').join('')+'</div>';
          const unc=(m==='ll'||m==='ov')?nom.llm_rationale.uncertainty:'';
          if(unc)html+='<div class="rat-unc">'+unc+'</div>';
          bd.innerHTML=html;
          rdet.appendChild(bd);
        }}
        rw.appendChild(rdet);
      }});
      body.appendChild(rw);
    }}
    det.appendChild(body);
    wrap.appendChild(det);
  }});
}}

/* ── Build Methods ── */
function buildMethods(){{
  const wrap=document.getElementById('meth-content');wrap.innerHTML='';
  const m=CUR_SUB;
  const V=D.validation;

  if(m==='ov'){{
    // Source code link
    // Source code link is in the top commentary
    // Method summary cards
    wrap.innerHTML+='<div class="sec"><h2>{t["sub_overall"]}</h2></div>';
    wrap.innerHTML+='<div class="mdesc">'+MT.ensemble+'</div>';
    wrap.innerHTML+='<div class="mcards">'
      +'<div class="mcard"><span class="mcard-tag st">Stats</span><div class="mcard-name">{t["sub_stats"]}</div><div class="mcard-desc">'+MT.tldrs.st+'</div></div>'
      +'<div class="mcard"><span class="mcard-tag ml">ML</span><div class="mcard-name">{t["sub_ml"]}</div><div class="mcard-desc">'+MT.tldrs.ml+'</div></div>'
      +'<div class="mcard"><span class="mcard-tag ll">LLM</span><div class="mcard-name">{t["sub_llm"]}</div><div class="mcard-desc">'+MT.tldrs.ll+'</div></div>'
      +'<div class="mcard"><span class="mcard-tag cr">Crowd</span><div class="mcard-name">{t["sub_crowd"]}</div><div class="mcard-desc">'+MT.tldrs.cr+'</div></div>'
    +'</div>';
    // Comparative analysis
    wrap.innerHTML+='<div class="mdesc">'+MT.comparative+'</div>';
    // Validation summary table
    wrap.innerHTML+='<div class="sec"><h2>'+(LANG==='cn'?'\\u9a8c\\u8bc1\\u7ed3\\u679c':'Validation Results')+'</h2></div>';
    let tblHtml='<table class="tbl"><thead><tr><th>Model</th><th>Accuracy</th><th>AUC</th><th>Coverage</th></tr></thead><tbody>';
    tblHtml+='<tr><td style="color:var(--stats);font-weight:600">Stats</td><td>'+pct(V.stats.overall_accuracy)+'</td><td>'+(V.stats.overall_auc?.toFixed(3)||'N/A')+'</td><td>'+V.stats.n_cat_years+' cat-yrs</td></tr>';
    tblHtml+='<tr><td style="color:var(--ml);font-weight:600">ML</td><td>'+pct(V.ml.overall_accuracy)+'</td><td>'+(V.ml.overall_auc?.toFixed(3)||'N/A')+'</td><td>'+V.ml.n_cat_years+' cat-yrs</td></tr>';
    tblHtml+='<tr><td style="color:var(--crowd);font-weight:600">Crowd</td><td>'+pct(V.gd.overall_accuracy)+'</td><td>'+(V.gd.overall_auc?.toFixed(3)||'N/A')+'</td><td>'+V.gd.n_cat_years+' cat-yrs</td></tr>';
    tblHtml+='<tr><td style="color:var(--llm);font-weight:600">LLM</td><td style="color:var(--text-muted)">N/A</td><td style="color:var(--text-muted)">N/A</td><td style="color:var(--text-muted)">&mdash;</td></tr>';
    tblHtml+='</tbody></table>';
    wrap.innerHTML+=tblHtml;
    // Year-by-year chart
    buildYearChart(wrap,V);
    // Per-category table
    buildCategoryTable(wrap,V);
    // Year-by-year detail
    buildYearDetail(wrap,V);
  }} else {{
    // Individual method
    wrap.innerHTML+='<div class="cbox"><h3>'+METHOD_LABELS[m]+' &mdash; TL;DR</h3><p>'+MT.tldrs[m]+'</p></div>';
    wrap.innerHTML+='<div class="mdesc">'+MT.descs[m]+'</div>';
    // Method-specific validation (if applicable)
    if(m==='st'||m==='ml'||m==='cr'){{
      const key={{st:'stats',ml:'ml',cr:'gd'}}[m];
      const mv=V[key];
      if(mv){{
        wrap.innerHTML+='<div class="sec"><h2>'+(LANG==='cn'?'\\u9a8c\\u8bc1':'Validation')+'</h2></div>';
        wrap.innerHTML+='<p style="font-size:.82rem;color:var(--text-light);margin:8px 0">'+(LANG==='cn'?'\\u51c6\\u786e\\u7387':'Accuracy')+': <strong>'+pct(mv.overall_accuracy)+'</strong> &middot; AUC: <strong>'+(mv.overall_auc?.toFixed(3)||'N/A')+'</strong> &middot; '+mv.n_cat_years+' cat-years</p>';
        buildCategoryTable(wrap,V,m);
      }}
    }}
  }}
}}

/* ── Charts & Tables ── */
function buildYearChart(wrap,V){{
  wrap.innerHTML+='<div class="chartbox"><div class="chart-title">'+(LANG==='cn'?'\\u9010\\u5e74\\u51c6\\u786e\\u7387':'Year-by-Year Accuracy')+'</div><div style="position:relative;height:200px"><canvas id="chart-yr"></canvas></div></div>';
  if(typeof Chart==='undefined')return;
  setTimeout(()=>{{
    const byYr=V.by_year,yL=[],ySt=[],yMl=[],yGd=[];
    for(const yr of Object.keys(byYr).sort()){{
      yL.push(yr);const res=byYr[yr];
      let sc=0,st=0,mc=0,mt=0,gc=0,gt=0;
      Object.values(res).forEach(r=>{{
        if(r.stats_correct!=null){{st++;if(r.stats_correct)sc++;}}
        if(r.ml_correct!=null){{mt++;if(r.ml_correct)mc++;}}
        if(r.gd_correct!=null){{gt++;if(r.gd_correct)gc++;}}
      }});
      ySt.push(st?Math.round(sc/st*100):null);
      yMl.push(mt?Math.round(mc/mt*100):null);
      yGd.push(gt?Math.round(gc/gt*100):null);
    }}
    const ctx=document.getElementById('chart-yr');
    if(ctx)new Chart(ctx,{{type:'bar',data:{{labels:yL,datasets:[
      {{label:'Stats',data:ySt,backgroundColor:'rgba(133,105,26,0.35)',borderColor:'#85691a',borderWidth:1,borderRadius:3}},
      {{label:'ML',data:yMl,backgroundColor:'rgba(123,82,212,0.4)',borderColor:'#7b52d4',borderWidth:1,borderRadius:3}},
      {{label:'Crowd',data:yGd,backgroundColor:'rgba(42,158,94,0.4)',borderColor:'#2a9e5e',borderWidth:1,borderRadius:3}},
    ]}},options:{{responsive:true,maintainAspectRatio:false,plugins:{{legend:{{position:'top',labels:{{boxWidth:8,padding:12}}}}}},scales:{{y:{{min:0,max:110,ticks:{{callback:v=>v+'%'}}}},x:{{grid:{{display:false}}}}}}}}}});
  }},100);
}}

function buildCategoryTable(wrap,V,method){{
  const ord=V.cat_order||[];
  const bc=V.by_category||{{}};
  let h='<div style="overflow-x:auto"><table class="tbl"><thead><tr><th>'+(LANG==='cn'?'\\u7c7b\\u522b':'Category')+'</th>';
  if(!method||method==='st')h+='<th>Stats Acc</th><th>Stats AUC</th>';
  if(!method||method==='ml')h+='<th>ML Acc</th><th>ML AUC</th>';
  if(!method||method==='cr')h+='<th>Crowd Acc</th><th>Crowd AUC</th>';
  h+='</tr></thead><tbody>';
  ord.forEach(k=>{{
    const d=bc[k];if(!d)return;
    h+='<tr><td>'+ck(k)+'</td>';
    const bar=v=>v!=null?'<span style="display:inline-block;height:5px;border-radius:2px;background:var(--gold-light);vertical-align:middle;margin-right:4px;width:'+Math.round(v*0.6)+'px"></span>':'';
    if(!method||method==='st'){{const a=d.stats_accuracy!=null?Math.round(d.stats_accuracy*100):null;h+='<td>'+(a!=null?bar(a)+a+'%':'&mdash;')+'</td><td>'+(d.stats_auc!=null?d.stats_auc.toFixed(3):'&mdash;')+'</td>';}}
    if(!method||method==='ml'){{const a=d.ml_accuracy!=null?Math.round(d.ml_accuracy*100):null;h+='<td>'+(a!=null?bar(a)+a+'%':'&mdash;')+'</td><td>'+(d.ml_auc!=null?d.ml_auc.toFixed(3):'&mdash;')+'</td>';}}
    if(!method||method==='cr'){{const a=d.gd_accuracy!=null?Math.round(d.gd_accuracy*100):null;h+='<td>'+(a!=null?bar(a)+a+'%':'&mdash;')+'</td><td>'+(d.gd_auc!=null?d.gd_auc.toFixed(3):'&mdash;')+'</td>';}}
    h+='</tr>';
  }});
  h+='</tbody></table></div>';
  wrap.innerHTML+=h;
}}

function buildYearDetail(wrap,V){{
  wrap.innerHTML+='<div class="sec"><h2>'+(LANG==='cn'?'\\u5404\\u5e74\\u5ea6\\u8be6\\u60c5':'Year-by-Year Detail')+'</h2></div>';
  const byYr=V.by_year||{{}};const ord=V.cat_order||[];
  let html='';
  for(const yr of Object.keys(byYr).sort()){{
    const res=byYr[yr];
    let sc=0,st=0,mc=0,mt=0,gc=0,gt=0;
    ord.forEach(k=>{{const r=res[k];if(!r)return;if(r.stats_correct!=null){{st++;if(r.stats_correct)sc++;}}if(r.ml_correct!=null){{mt++;if(r.ml_correct)mc++;}}if(r.gd_correct!=null){{gt++;if(r.gd_correct)gc++;}}}});
    const hdrTxt=yr+' &mdash; Stats '+sc+'/'+st+' &middot; ML '+(mt?mc+'/'+mt:'&mdash;')+' &middot; Crowd '+(gt?gc+'/'+gt:'&mdash;');
    let rows='';
    ord.forEach(k=>{{const r=res[k];if(!r)return;
      const ok=v=>v==null?'<span style="color:var(--text-muted)">&mdash;</span>':(v?'<span class="ico-ok">\\u2713</span>':'<span class="ico-ms">\\u2717</span>');
      rows+='<tr><td>'+ck(k)+'</td><td style="text-align:center">'+ok(r.stats_correct)+'</td><td>'+r.stats_pred+'</td><td style="text-align:center">'+ok(r.ml_correct)+'</td><td>'+r.ml_pred+'</td><td style="text-align:center">'+ok(r.gd_correct)+'</td><td>'+r.gd_pred+'</td><td style="font-weight:600">'+r.actual+'</td></tr>';
    }});
    html+='<div class="yritem"><div class="yrhdr" onclick="this.classList.toggle(\\'open\\');this.nextElementSibling.classList.toggle(\\'open\\')"><h3>'+hdrTxt+'</h3><span class="ychev">\\u25bc</span></div><div class="yrtblwrap"><table class="tbl"><thead><tr><th>Category</th><th style="text-align:center">St</th><th>Stats</th><th style="text-align:center">ML</th><th>ML</th><th style="text-align:center">Cr</th><th>Crowd</th><th>Actual</th></tr></thead><tbody>'+rows+'</tbody></table></div></div>';
  }}
  wrap.innerHTML+=html;
}}

/* ── Init ── */
document.addEventListener('DOMContentLoaded',()=>{{
  buildContent();
}});
</script>
<script src="../assets/js/oscar-nav.js"></script>
</body>
</html>'''


def main():
    ap = argparse.ArgumentParser(description='Generate Oscar 2026 prediction HTML pages')
    default_out = os.path.join(os.path.dirname(__file__), '..', '..', 'mengtingwan.github.io', 'oscars')
    ap.add_argument('--output-dir', default=default_out,
                    help='Output directory for HTML pages (default: ../mengtingwan.github.io/oscars/)')
    args = ap.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    for lang_key in ['en', 'cn']:
        t = TRANS[lang_key]
        html = build_page(t)
        filename = 'oscar2026.html' if lang_key == 'en' else 'oscar2026_cn.html'
        path = os.path.join(args.output_dir, filename)
        with open(path, 'w', encoding='utf-8') as f:
            f.write(html)
        print(f'  {path} ({os.path.getsize(path) / 1024:.0f} KB)')

    print('Done.')


if __name__ == '__main__':
    main()
